name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          
      - name: Print COSMOS_URI
        run: echo $COSMOS_URI
        env:
          COSMOS_URI: ${{ secrets.COSMOS_URI }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.ACR_REGISTRY }}/pctmaphelloworld:${{ github.sha }}
        env:
          COSMOS_URI: ${{ secrets.COSMOS_URI }}

      - name: Deploy to Azure App Services
        uses: azure/webapps-deploy@v2
        with:
          app-name: pct-map
          publish-profile: ${{ secrets.AZURE_APP_SERVICE_PUBLISH_PROFILE }}
          images: |
            ${{ secrets.ACR_REGISTRY }}/pctmaphelloworld:${{ github.sha }}
          env: COSMOS_URI=${{ secrets.COSMOS_URI }}
